language: php

php:
  - "5.4"
  - "5.3"
  - "5.2"

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

matrix:
  allow_failures:
    - php: 5.4

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS wolfcms_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database wolfcms_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS wolfcms_tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database wolfcms_tests;'; fi"
  - git clone --depth=100 --quiet git://github.com/wolfcms/wolfcms-phpunit.git test

script: phpunit test/*
